/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.weaved.server.query.text;

import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Ruchira
 */
public class TextOutputCreator extends javax.swing.JPanel {

    /**
     * Creates new form TextOutputCreatoNew
     */
    public TextOutputCreator() {
        initComponents();
        setLayout(new FlowLayout());

    }
    /**
     * Creates new form TextOutputCreatorNew
     */
   
private String filePath;
    private ArrayList<String> fileNames;

    public TextOutputCreator(ArrayList<String> fNames, String fPath) {
        this.filePath = fPath;        // "C:\\Users\\Ruchira\\Documents\\NetBeansProjects\\Weave-D\\Input\\Files\\Text\\";
        this.fileNames = fNames;   //{"1_Easy_Mid_RockClimbing_557","1_Easy_Mid_snowboarding_23","2_Easy_Close_polo_9","1_Easy_Mid_RockClimbing_557","1_Easy_Mid_snowboarding_23","2_Easy_Close_polo_9","2_Easy_Far_Rowing_234"};
        initComponents();
    }

    /**
     * Creates new 
     */
    public JPanel getTextOutputPanel() {
        JPanel panelHolder = new JPanel();
       // panelHolder.setLayout(new FlowLayout());
        if (fileNames != null && filePath != null) {            
            panelHolder.setLayout(new GridLayout(fileNames.size(), 1, 1, 4));
            for (String fName : fileNames) {
                TextPanel tp = new TextPanel(fName, filePath);
                panelHolder.add(tp);
            }
        } else {
            panelHolder.add(new JLabel("Error"));
        }
        return panelHolder;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
