/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.weaved.server.query.text;

import javax.swing.JOptionPane;

/**
 *
 * @author Ruchira
 */
public class TextPanel extends javax.swing.JPanel {

    private String txtFileName;
    private String filePath;
    private String absFilePath;

    /**
     * Creates new form TextPanel
     */
    public TextPanel(String txtFileName, String txtFilePath) {
        // holds the file name
        this.txtFileName = txtFileName;

        // holds the location of the text files
        this.filePath = txtFilePath;

        // creates a path using filePath + txtFileName
        this.absFilePath = filePath + txtFileName + ".txt";

        initComponents();
        
        fileNameLbl.setText("<html><body><U>" + txtFileName + "</U><body></html>");
        //txtSummaryArea.setWrapStyleWord(true);
        txtSummaryArea.setLineWrap(true);
        txtSummaryArea.setText(TextSummaryCreator.getTextSummerty(absFilePath, 100));
        
        setSize(432, 150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtSummaryArea = new javax.swing.JTextArea();
        fileNameLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(227, 227, 227));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        setAutoscrolls(true);
        setMinimumSize(new java.awt.Dimension(320, 90));
        setName("test"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setMaximumSize(null);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(312, 43));

        txtSummaryArea.setEditable(false);
        txtSummaryArea.setColumns(5);
        txtSummaryArea.setRows(5);
        txtSummaryArea.setAutoscrolls(false);
        txtSummaryArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtSummaryArea.setMaximumSize(null);
        txtSummaryArea.setMinimumSize(new java.awt.Dimension(4, 12));
        jScrollPane1.setViewportView(txtSummaryArea);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        fileNameLbl.setText("txtFile");
        fileNameLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fileNameLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fileNameLblMouseClicked(evt);
            }
        });
        add(fileNameLbl, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void fileNameLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fileNameLblMouseClicked
         try {
            ProcessBuilder proc = new ProcessBuilder("notepad.exe", filePath + txtFileName + ".txt");
            proc.start();
        } catch (Exception hj) {
            System.out.println("Error:" + hj);
        }
    }//GEN-LAST:event_fileNameLblMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fileNameLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtSummaryArea;
    // End of variables declaration//GEN-END:variables
}
